services:
  - type: web
    name: memorial-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: memorial-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        fromSecret: true
      - key: AWS_SECRET_ACCESS_KEY
        fromSecret: true
      - key: AWS_BUCKET_NAME
        value: "your-bucket-name"
      - key: AWS_REGION
        value: "us-east-1"

databases:
  - name: memorial-db
    ipAllowList: [] 