services:
  - type: web
    name: memorial-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: memorial-db
          property: connectionString
      - key: USE_LOCAL_STORAGE
        value: "False"
      - key: AWS_ACCESS_KEY_ID
        fromSecret: true
      - key: AWS_SECRET_ACCESS_KEY
        fromSecret: true
      - key: AWS_BUCKET_NAME
        fromSecret: true
      - key: AWS_REGION
        value: "us-east-1"
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_pre_ping": true}'

databases:
  - name: memorial-db
    ipAllowList: []  # This means the database accepts connections from all Render services 
    plan: starter # or whatever plan you're using 