services:
  - type: web
    name: memorial-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: memorial-db
          property: connectionString

databases:
  - name: memorial-db
    ipAllowList: [] 